### ISSUE TITLE
Does not work on iOS 8 Cordova 5.4.1

### ISSUE THREAD

**Issue by ShamimIslam** [appfeel/cordova-push-notifications#4]
Love your plugin. Simplest of all the versions I've seen and it JUST WORKS.

Until I had to upgrade to Cordova 5.4.1.

Now I have 2 items:

1 item one is here:

cordova-push-notifications/PushPlugin.m:203:23: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
        [self.webView stringByEvaluatingJavaScriptFromString:jsCallBack];

**Comment by miqmago** [comment]
Same as other issue, take a look on https://github.com/phonegap/phonegap-plugin-push

If you really think this is simpler, maybe we can take a look on how to update this plugin. But I really think that it does not make sense, having that there is an official mantained one.

**Comment by ShamimIslam** [comment]
Actually in my code review, the apfeel version was so much simpler. There
just seemed some type changes from different veriosn of iOS and a few
additional arguments that required defaults. Do we really need all the
stuff in the new one? It seem so complex for something so simple - "remind
me when something happens". The old one even had code samples for Windows
10 and the rest.

Do you know someone that has migrated to the new one? I don't want to break
my build but XDK is deprecating 5.4.1.
